### ISSUE TITLE
Buttons disappear immediately, if another message from the bot follows

### ISSUE THREAD

**Issue by dfiore-ch** [mrbot-ai/rasa-webchat#55]
My bot should utter a message with two buttons and right away another, additional message. Unfortunately the buttons only show up for a fraction of a second and disappear, when the other message from the bot is uttered.

In my point of view the buttons should stay in the chat protocol as long as the user has not answered.

Here how my rasa template lookes like:
```
utter_intro1:
  - text: "Hi I am ... These are my use cases... "
    buttons:
    - title: "Use Case 1"
      payload: "/a"
    - title: "Use Case 2"
      payload: "/b"
    - title: "Use Case 3"
      payload: "/c"
utter_intro2:
  - text: "...but I am also happy to answer other questions from you..." 
```
