### ISSUE TITLE
How to create a Button to go to an URL?

### ISSUE THREAD

**Issue by diegodorgam** [mrbot-ai/rasa-webchat#90]
I've been trying to add some interface elements, but until now I was only able to create the buttons with the payload method, like this:
```yaml
  utter_equipamentos_estacoes_emprestimo:
    - text: | 
        ótimo!
        você pode solicitar empréstimos de equipamentos por  
        `Curta`(até 7 dias),  
        `Média` (até 3 meses) ou   
        `Longa` (mais que 3 meses) duração.  

      buttons: 
        - title: "Curta"
          payload: "/equipamentos_estacoes_emprestimo_curta"
        - title: "Média"
          payload: "/equipamentos_estacoes_emprestimo_media"
        - title: "Longa"
          payload: "/equipamentos_estacoes_emprestimo_longa"
```
this button will send back an intent to rasa core, which is pretty cool for navigation purposes.

But now I need to send buttons to visit an URL, to make the browser got to a new location.

I've trie this facebook notation:
```json
        "buttons":[
          {
            "type":"web_url",
            "url":"https://www.messenger.com/",
            "title":"URL Button",
            "webview_height_ratio": "full"
          }
        ]
```
and it just didn't rendered the code.

Tried this approach also:
```yaml
  utter_equipamentos_estacoes_devolucao:
    - text: | 
          response text...
      attachment:
        type: "template"
        payload:
          template_type: "generic"
          elements:
            - title: "escolha"
              buttons:
                - title: "Open URL 1"
                  url: "http://...."
                - title: "Open URL 2"
                  url: "http://..."
```

and this printed a second message with `Attachment:....code` the code in json format inside as text response.

Any ideas on how to implement these elements using the utterances of domain.yaml?
